[package]
authors = ["kangalioo <jannik.a.schaper@web.de>"]
edition = "2018"
name = "poise"
version = "0.1.0"
description = "A Discord bot framework for serenity"
documentation = "https://kangalioo.github.io/poise/"
license = "MIT"
repository = "https://github.com/kangalioo/poise/"

[dependencies]
tokio = { version = "1.4.0", default-features = false } # for async in general
futures-core = { version = "0.3.13", default-features = false } # for async in general
futures-util = { version = "0.3.13", default-features = false } # for async in general
once_cell = { version = "1.7.2", default-features = false, features = ["std"] } # to store and set user data
poise_macros = { path = "macros" }
async-trait = { version = "0.1.48", default-features = false } # various traits
regex = { version = "1.5.4", default-features = false, features = ["std"] } # prefix
log = { version = "0.4.14", default-features = false } # warning about weird state
derivative = "2.2.0"

[dependencies.serenity]
default-features = false
features = ["builder", "cache", "client", "gateway", "model", "utils", "unstable_discord_api", "collector"]

# version = "0.10.5"

git = "https://github.com/serenity-rs/serenity"
branch = "next"

# git = "https://github.com/kangalioo/serenity"
# branch = "poise-tailored"

# path = "../_downloaded/serenity"

[dev-dependencies]
# For the examples
tokio = { version = "1.4.0", features = ["rt-multi-thread"] }
futures = { version = "0.3.13", default-features = false }
# poise = { path = ".", features = ["collector"] } # avoids the need for "--features collector"

[features]
default = ["serenity/rustls_backend"]
# No-op feature because serenity/collector is now enabled by default
collector = []
