[package]
authors = ["kangalioo <jannik.a.schaper@web.de>"]
edition = "2018"
name = "poise"
version = "0.1.0"
description = "A Discord bot framework for serenity"
documentation = "https://kangalioo.github.io/poise/"
license = "MIT"
repository = "https://github.com/kangalioo/poise/"

[dependencies]
tokio = "1.4.0" # for async in general
futures = "0.3.13" # for async in general
chrono = "0.4.19" # interoperate with serenity timestamps
once_cell = "1.7.2" # to store and set user data
serde_json = "1" # needed for interacting with some parts of the Discord API
poise_macros = { path = "macros" }
async-trait = "0.1.48" # PopArgumentAsync trait
regex = "1.5.4" # prefix

[dependencies.serenity]
default-features = false
features = ["builder", "cache", "client", "gateway", "model", "utils", "rustls_backend", "unstable_discord_api"]

# version = "0.10.5"

git = "https://github.com/serenity-rs/serenity"
branch = "next"

# git = "https://github.com/kangalioo/serenity"
# branch = "poise-tailored"

# path = "../_downloaded/serenity"

[dev-dependencies]
# For the examples
tokio = { version = "1.4.0", features = ["rt-multi-thread"] }

[features]
collector = ["serenity/collector"]
